forge 'http://forge.puppetlabs.com'

mod 'puppetlabs/ruby', '0.4.0'
mod 'puppetlabs/gcc', '0.3.0'
#mod 'puppetlabs/pe_gem', '0.1.1'
mod 'croddy/make', '0.0.5'
mod 'puppetlabs/vcsrepo', '1.3.1'
mod 'puppetlabs/git', '0.4.0'
mod 'puppetlabs/inifile', '1.4.2'
mod 'puppetlabs/stdlib', '4.9.0'
mod 'zack/r10k', '3.1.1'
mod 'hunner/hiera', '1.2.0'
mod 'abrader/gms', '1.0.0'
